---
- name: reload wireguard daemon
  systemd:
    daemon_reload: true
  when: ansible_facts.service_mgr == 'systemd'

- name: restart wireguard
  service:
    name: >-
      {{
      'wg-quick.wg0' if ansible_facts.distribution == 'Alpine'
      else 'wg-quick@wg0'
      }}
    enabled: true
    state: restarted
