---
- name: restart wireguard
  block:
    - name: systemctl daemon-reload
      ansible.builtin.systemd_service:
        daemon_reload: true
      when: ansible_service_mgr == 'systemd'

    - name: restart service
      ansible.builtin.service:
        name: wg-quick@wg0
        enabled: true
        state: restarted
