- name: Configure hosts (role-based)
  hosts: all
  become: true
  roles:
    - role: postmarketOS
      tags: [postmarketOS, pmOS]
      when: pmOS is defined

    - role: common
      tags: [common]

    - role: swap
      tags: [swap]

    - role: zram
      tags: [zram]

    - role: home
      tags: [home]
      become: false

    - role: boinc
      tags: [boinc]
      when: "'boinc' in group_names"

    - role: wireguard
      tags: [wireguard]
      when: wg_ip is defined

    - role: firewall
      tags: [firewall]

    - role: kube
      tags: [kube]
      when: "'kube' in group_names"
