---
- include_tasks: arch.yml
  when: ansible_facts['distribution'] == 'Arch'

- include_tasks: ubuntu.yml
  when: ansible_facts['distribution'] == 'Ubuntu'

- include_tasks: alpine.yml
  when: ansible_facts['distribution'] == 'Alpine'
