---
- name: Arch only
  include_tasks: arch.yml
  when: ansible_facts['distribution'] == 'Archlinux'

- name: Ubuntu only
  include_tasks: ubuntu.yml
  when: ansible_facts['distribution'] == 'Ubuntu'

- name: Alpine only
  include_tasks: alpine.yml
  when: ansible_facts['distribution'] == 'Alpine'
