#!/bin/bash

set -Eeu

move_mnt(){
    mount --bind "$1" "$2"
    umount "$1"
}

TMP=$(mktemp -d)
MNT=$(realpath "$1")

if ! mountpoint -q "$MNT"; then
    [ ! -d "$MNT" ] && exit 1

    DEV=$(zramctl -f -s $2)
    mkfs.ext4 -q $DEV
    mount $DEV $TMP

    rsync -a "$MNT/" $TMP/
    move_mnt $TMP "$MNT"
else
    move_mnt "$MNT" $TMP
    rsync -a --exclude='lost+found' --delete-after $TMP/ "$MNT/"

    DEV=$(awk -v tmp="$TMP" '$2 == tmp {print $1}' /proc/mounts)
    umount $TMP
    zramctl -r $DEV
fi
