---
- name: /etc/swapfile
  include_tasks: swapfile.yml

- name: systemd-zram-generator
  include_tasks: systemd-zram-generator.yml
  when:
    - ansible_facts.service_mgr == "systemd"
    - ansible_facts.distribution in ["Ubuntu", "Archlinux"]

- name: zarm-init
  include_tasks: zram-init.yml
  when:
    - ansible_facts.service_mgr == "openrc"
    - ansible_facts.distribution == "Alpine"
