---
- name: Install package
  pacman:
    state: present
    package: zram-generator

- name: Create service
  copy:
    dest: /etc/systemd/zram-generator.conf
    content: |
      [zram0]
      zram-size = min(ram / 2, 8192)
  register: zram_service

- name: Enable and start service
  systemd:
    name: zram-generator
    enabled: yes
    state: restarted
    daemon_reload: yes
  when: zram_service.changed
