---
- name: Archlinux or Ubuntu only
  include_tasks: arch_ubuntu.yml
  when: ansible_facts['distribution'] in ['Archlinux','Ubuntu']

- name: Alpine only
  include_tasks: alpine.yml
  when: ansible_facts['distribution'] == 'Alpine'
