---
- name: Install zram-tools
  apt:
    update_cache: true
    package: zram-tools
    state: present

- name: Configure zramswap ALGO
  lineinfile:
    path: /etc/default/zramswap
    regexp: "^#?ALGO="
    line: "ALGO=zstd"
  register: zram_algo

- name: Configure zramswap SIZE
  lineinfile:
    path: /etc/default/zramswap
    regexp: "^#?PERCENT="
    line: "PERCENT=50"
  register: zram_size

- name: Enable and start zramswap
  systemd:
    name: zramswap
    enabled: yes
    state: restarted
    daemon_reload: yes
  when: zram_algo.changed or zram_size.changed
