---
- name: Make sure ~/.local exists
  file:
    path: ~/.local
    state: directory
    mode: 0755

- name: Servers only
  include_tasks: servers.yml
  when:
    - "'servers' in group_names"
    - "'laptops' not in group_names"

- name: Laptops only
  include_tasks: laptops.yml
  when: "'laptops' in group_names"
