---
- name: Copy iptables rules
  copy:
    dest: /root/iptables-rules.sh
    src: "{{ playbook_dir }}/files/iptables-rules.sh"
    mode: "0700"
  register: iptables_ttj

- name: Apply rules atomically
  shell: /root/iptables-rules.sh
  when: iptables_ttj.changed
