---
- name: Ensure nftables is installed
  ansible.builtin.package:
    name: nftables
    state: present

- name: Copy base ruleset
  copy:
    path: >-
      /etc/nftables.{{
        'nft' if ansible_distribution == 'Alpine' else 'conf'
      }}
    src: base.nft
  register: base

- name: Ensure {{ nftd }} exists
  file:
    path: "{{ nftd }}"
    state: directory
    mode: "0755"

- name: Render rules to {{ nftd }}
  template:
    src: ruleset.nft.j2
    dest: "{{ nftd }}/01_ttj.nft"
    mode: "0644"
  register: rules

- name: Ensure drop-in snippets are parsed
  lineinfile:
    path: >-
      /etc/nftables.{{
        'nft' if ansible_facts.distribution == "Alpine" else 'conf'
      }}
    line: include "{{ nftd }}/*.nft"

- name: Reload ruleset
  when: base.changed or rules.changed
  ansible.builtin.service:
    name: nftables
    enabled: true
    status: restarted
