---
- name: Ensure nftables is installed
  ansible.builtin.package:
    name: nftables
    state: present

- name: Copy base ruleset
  copy:
    dest: >-
      /etc/nftables.{{
        'nft' if ansible_facts.distribution == 'Alpine' else 'conf'
      }}
    src: base.nft
  register: base

- name: Ensure {{ nftd }} exists
  file:
    path: "{{ nftd }}"
    state: directory
    mode: "0755"

- name: Render rules to {{ nftd }}
  template:
    src: ruleset.nft.j2
    dest: "{{ nftd }}/01_ttj.nft"
    mode: "0644"
  register: rules

- name: Ensure drop-in snippets are parsed
  lineinfile:
    path: >-
      /etc/nftables.{{
        'nft' if ansible_facts.distribution == "Alpine" else 'conf'
      }}
    line: include "{{ nftd }}/*.nft"

- name: Reload nft ruleset
  when: base.changed or rules.changed
  ansible.builtin.service:
    name: nftables
    enabled: true
    state: restarted

- name: Gather service facts
  ansible.builtin.service_facts:

- name: Restart services if they exist
  ansible.builtin.service:
    name: "{{ item }}"
    enabled: true
    state: restarted
  loop:
    - k0scontroller
    - docker
  when:
    - base.changed or rules.changed
    - item + '.service' in ansible_facts.services

- name: Stop iptables
  when: "'iptables.service' in ansible_facts.services"
  ansible.builtin.service:
    name: iptables
    enabled: false
    state: stopped
