---
- name: Ensure {{ nftd }} exists
  file:
    path: "{{ nftd }}"
    state: directory
    mode: "0755"

- name: Render rules to {{ nftd }}
  template:
    src: ruleset.nft.j2
    dest: "{{ nftd }}/100-ttj.nft"
    mode: "0644"
  register: rules

- name: Ensure drop-in snippets are parsed
  lineinfile:
    path: >-
      /etc/nftables.{{
        'nft' if ansible_facts.distribution == "Alpine" else 'conf'
      }}
    line: include "{{ nftd }}/*.nft"

- name: Reload ruleset
  ansible.builtin.command: nft -f "{{ nftd }}/100-ttj.nft"
  when: rules.changed
