---
- name: Mount / shared
  copy:
    dest: /etc/local.d/mount.start
    mode: "0755"
    content: |
      #!/bin/sh
      mount --make-rshared /

- name: Enable local service
  service:
    name: local
    enabled: true
