---
- name: Configure hosts
  hosts: all
  vars_files:
    - group_vars/all.yml
  tasks:
    - name: Run as root
      become: true
      block:
        - name: Install common utils
          package:
            name: "{{ utils }}"
            state: present

        - name: Set locale
          copy:
            dest: /etc/locale.conf
            owner: root
            group: root
            mode: "0644"
            content: |
              LANG=en_US.UTF-8
              LANGUAGE=en_US.UTF-8
              LC_MESSAGES=en_US.UTF-8

              LC_ADDRESS={{ default_locale }}
              LC_COLLATE={{ default_locale }}
              LC_CTYPE={{ default_locale }}
              LC_IDENTIFICATION={{ default_locale }}
              LC_MEASUREMENT={{ default_locale }}
              LC_MONETARY={{ default_locale }}
              LC_NAME={{ default_locale }}
              LC_NUMERIC={{ default_locale }}
              LC_PAPER={{ default_locale }}
              LC_TELEPHONE={{ default_locale }}
              LC_TIME={{ default_locale }}

        - name: Configure !swapfile on Arch & Ubuntu
          when: ansible_facts["distribution"] in ["Ubuntu", "Arch"]
          block:
            - name: Determine swapfile size
              set_fact:
                swap_size: "{{ '1G' if ansible_facts['memtotal_mb'] > 1024 else '4G' }}"

            - name: Create, secure, and format swap file
              shell: |
                fallocate -l {{ swap_size }} /swapfile &&
                chmod 0600 /swapfile &&
                mkswap /swapfile
              args:
                creates: /swapfile

            - name: Ensure swap is in fstab and active
              lineinfile:
                path: /etc/fstab
                regexp: "^/swapfile"
                line: "/swapfile none swap defaults,pri=10,discard 0 0"
              register: swap_fstab

            - name: Activate swap immediately
              command: swapon -a
              when: swap_fstab.changed

        - name: Enable zram on Arch
          when: ansible_facts["distribution"] == "Arch"
          block:
            - name: Install package
              pacman:
                state: present
                package: zram-generator

            - name: Create service
              copy:
                dest: /etc/systemd/zram-generator.conf
                content: |
                  [zram0]
              register: zram_service

            - name: Enable and start service
              systemd:
                name: zram-generator
                enabled: yes
                state: restarted # Restarted ensures it applies changes if you edit the task
                daemon_reload: yes
              when: zram_service.changed

        - name: Enable zram on Ubuntu
          when: ansible_facts["distribution"] == "Ubuntu"
          block:
            - name: Install zram-tools
              apt:
                update_cache: true
                package: zram-tools
                state: present

            - name: Configure zramswap ALGO
              lineinfile:
                path: /etc/default/zramswap
                regexp: "^#?ALGO="
                line: "ALGO=zstd"
              register: zram_algo

            - name: Configure zramswap SIZE
              lineinfile:
                path: /etc/default/zramswap
                regexp: "^#?PERCENT="
                line: "PERCENT=50"
              register: zram_size

            - name: Enable and start zramswap
              systemd:
                name: zramswap
                enabled: yes
                state: restarted # Restarted ensures it applies changes if you edit the task
                daemon_reload: yes
              when: zram_algo.changed or zram_size.changed

        - name: Enable zram on Alpine
          when: ansible_facts["distribution"] == "Alpine"
          block:
            - name: Install zram-init
              apk:
                state: present
                name: zram-init

            - name: Configure zram-init
              lineinfile:
                path: /etc/conf.d/zram-init
                regexp: "^num_devices="
                line: "num_devices=1"
              register: zram_init_conf

            - name: Enable and start service
              service:
                state: restarted
                enabled: true
                name: zram-init
              when: zram_init_conf.changed

    - when: "'servers' in group_names"
      block:
        - name: Copy ~/.* to server
          copy:
            dest: "~/{{ item }}"
            src: "{{ playbook_dir }}/../{{ item }}"
          loop: "{{ conf_files }}"

        - name: Sync ~/bin to server
          synchronize:
            dest: ~/bin/
            src: "{{ playbook_dir }}/../bin/"
            delete: true

    - when: "'laptops' in group_names"
      block:
        - name: Symlink ~/.* on laptop
          file:
            path: "~/{{ item }}"
            src: "{{ playbook_dir }}/../{{ item }}"
            state: link
          loop: "{{ conf_files }}"

        - name: Symlink ~/bin on laptop
          file:
            path: ~/bin
            src: "{{ playbook_dir }}/../bin"
            state: link

        - name: Deploy user-level systemd services
          file:
            path: "~/.config/systemd/user/{{ item }}.service"
            src: "{{ playbook_dir }}/../.config/systemd/user/{{ item }}.service"
            state: link
          loop: "{{ systemd_user_services }}"

        - name: Enable & start user-level systemd services
          systemd:
            name: "{{ item }}"
            state: started
            enabled: true
            scope: user
          loop: "{{ systemd_user_services }}"

- name: Ensure BOINC is installed
  hosts: boinc
  vars_files:
    - group_vars/all.yml
  tasks:
    - name: Run as root
      become: true
      block:
        - name: Install BOINC packages on Arch hosts
          when: ansible_facts["distribution"] == "Arch"
          pacman:
            name: "{{ boinc_arch }}"
            state: present
            update_cache: yes

        - name: Install BOINC packages on Ubuntu hosts
          when: ansible_facts["distribution"] == "Ubuntu"
          apt:
            name: "{{ boinc_ubuntu }}"
            state: present
            update_cache: yes

        - name: Ensure boinc-client service is running
          systemd:
            name: boinc-client
            state: started
            enabled: yes

        - name: Add user to boinc group
          user:
            name: "{{ ansible_facts['user_id'] }}"
            groups: boinc
            append: yes

    - name: Attach to BAM
      shell: >-
        boinccmd
        --join_acct_mgr https://bam.boincstats.com/
        "{{ lookup('env', 'BAM_USERNAME') }}"
        "{{ lookup('env', 'BAM_PASSWORD') }}"
      args:
        creates: /var/lib/boinc/acct_mgr_login.xml
      when: >
        lookup('env', 'BAM_USERNAME') | length > 0 and
        lookup('env', 'BAM_PASSWORD') | length > 0
