---
- name: Configure new host
  hosts: all
  vars_files:
    - group_vars/all.yml
  tasks:
    - name: Run as root
      become: true
      block:
        - name: Set locale
          copy:
            dest: /etc/locale.conf
            owner: root
            group: root
            mode: "0644"
            content: |
              LANG=en_US.UTF-8
              LANGUAGE=en_US.UTF-8
              LC_MESSAGES=en_US.UTF-8

              LC_ADDRESS={{ default_locale }}
              LC_COLLATE={{ default_locale }}
              LC_CTYPE={{ default_locale }}
              LC_IDENTIFICATION={{ default_locale }}
              LC_MEASUREMENT={{ default_locale }}
              LC_MONETARY={{ default_locale }}
              LC_NAME={{ default_locale }}
              LC_NUMERIC={{ default_locale }}
              LC_PAPER={{ default_locale }}
              LC_TELEPHONE={{ default_locale }}
              LC_TIME={{ default_locale }}

        - name: Determine swapfile size
          set_fact:
            swap_size: "{{ '1G' if ansible_facts['memtotal_mb'] > 1024 else '4G' }}"

        - name: Create, secure, and format swap file
          shell: |
            fallocate -l {{ swap_size }} /swapfile &&
            chmod 0600 /swapfile &&
            mkswap /swapfile
          args:
            creates: /swapfile

        - name: Ensure swap is in fstab and active
          lineinfile:
            path: /etc/fstab
            regexp: "^/swapfile"
            line: "/swapfile none swap defaults,pri=10 0 0"
          register: swap_fstab

        - name: Activate swap immediately
          command: swapon -a
          when: swap_fstab.changed

        - name: Ensure zram module is loaded
          copy:
            dest: /etc/modules-load.d/zram.conf
            content: zram

        - name: Create zram-setup service
          copy:
            dest: /etc/systemd/system/zram-setup.service
            content: |
              [Unit]
              Description=Setup zram swap
              After=multi-user.target

              [Service]
              Type=oneshot
              RemainAfterExit=yes
              ExecStartPre=/sbin/modprobe zram

              # Reset ensures we can change algorithm/size if already initialized
              ExecStartPre=-/bin/sh -c 'echo 1 > /sys/block/zram0/reset'
              ExecStartPre=/bin/sh -c 'echo zstd > /sys/block/zram0/comp_algorithm'
              ExecStartPre=/bin/sh -c 'echo {{ (ansible_facts["memtotal_mb"] * 4 // 10) }}M > /sys/block/zram0/disksize'
              ExecStart=/sbin/mkswap /dev/zram0
              ExecStartPost=/sbin/swapon /dev/zram0 -p 100
              ExecStop=/sbin/swapoff /dev/zram0

              [Install]
              WantedBy=multi-user.target
          register: zram_service

        - name: Enable and start zram-setup
          systemd:
            name: zram-setup
            enabled: yes
            state: restarted # Restarted ensures it applies changes if you edit the task
            daemon_reload: yes
          when: zram_service.changed

    - name: Servers-only
      when: "'servers' in group_names"
      block:
        - name: Copy ~/.*
          copy:
            dest: "~/{{ item }}"
            src: "{{ item }}"
          loop: "{{ dotfiles_in_home }}"

    - name: Laptops-only
      when: "'laptops' in group_names"
      block:
        - name: Symlink ~/.*
          file:
            path: "~/{{ item }}"
            src: "{{ item }}"
            state: link
          loop: "{{ dotfiles_in_home }}"

        - name: Enable & start user-level systemd services
          systemd:
            name: "{{ ansible_facts['playbook_dir'] }}/../.config/systemd/user/{{ item }}"
            state: started
            enabled: true
            scope: user
          loop: "{{ systemd_user_services }}"

- name: Ensure BOINC is installed
  hosts: boinc
  become: true
  vars_files:
    - group_vars/all.yml
  tasks:
    - name: Install BOINC packages on Arch hosts
      when: ansible_facts["distribution"] == "Arch"
      pacman:
        name: "{{ boinc_arch }}"
        state: present
        update_cache: yes

    - name: Install BOINC packages on Ubuntu hosts
      when: ansible_facts["distribution"] == "Ubuntu"
      apt:
        name: "{{ boinc_ubuntu }}"
        state: present
        update_cache: yes

    - name: Ensure boinc-client service is running
      systemd:
        name: boinc-client
        state: started
        enabled: yes

    - name: Attach to BAM
      shell: >-
        boinccmd
        --join_acct_mgr https://bam.boincstats.com/
        {{ BAM_USERNAME }}
        {{ BAM_PASSWORD }}
      args:
        creates: /var/lib/boinc/acct_mgr_login.xml
      when: >-
        BAM_USERNAME is defined and 
        BAM_PASSWORD is defined
