---
- name: Install packages
  package:
    name:
      # required by Longhorn
      - open-iscsi

      # for the vmstat 1 command
      - procps
      - yq
    state: present

- name: Enable & start open-iscsi
  service:
    name: iscsid
    state: started
    enabled: true

- name: Alpine agents
  include_tasks: alpine-agent.yml
  when: ansible_facts.distribution == "Alpine"
