---
- name: Copy script
  copy:
    dest: /usr/local/bin
    src: zram-dir
    mode: "0755"

- name: Copy service
  copy:
    dest: /etc/init.d/
    src: zram-dirs
    mode: "0755"

- name: Enable service
  service:
    name: zram-dirs
    enabled: true
