---
- name: Copy script
  copy:
    dest: /usr/local/bin
    src: zram-dir
    mode: "0755"

- name: Copy service
  copy:
    dest: /etc/init.d/zram-dir
    src: zram-dir.service
    mode: "0755"

- name: Create links to service
  file:
    path: /etc/init.d/zram-dir.{{ item.path | replace('/', '%2F') }}.{{ item.size }}
    src: /etc/init.d/zram-dir
    state: link
  loop: "{{ zram_dirs }}"
