---
- name: Install BOINC packages
  when: ansible_facts['distribution'] in ["Ubuntu", "Archlinux"]
  package:
    name: >-
      {{
        boinc_ubuntu if ansible_facts['distribution'] == 'Ubuntu'
        else boinc_arch
      }}
    state: present
    update_cache: yes

- name: Enable & start boinc-client
  systemd:
    name: boinc-client
    state: started
    enabled: yes

- name: Add user to boinc group
  user:
    name: "{{ ansible_facts['user_id'] }}"
    groups: boinc
    append: yes

- name: Attach to BAM
  become: false
  shell: >-
    boinccmd
    --join_acct_mgr https://bam.boincstats.com/
    "{{ lookup('env', 'BAM_USERNAME') }}"
    "{{ lookup('env', 'BAM_PASSWORD') }}"
  args:
    creates: /var/lib/boinc/acct_mgr_login.xml
  when: >
    lookup('env', 'BAM_USERNAME') | length > 0 and
    lookup('env', 'BAM_PASSWORD') | length > 0
