---
- name: Copy ~/.* to server
  copy:
    dest: "~/{{ item }}"
    src: "{{ playbook_dir }}/../{{ item }}"
  loop: "{{ conf_files }}"

- name: Sync ~/bin to server
  synchronize:
    dest: ~/bin/
    src: "{{ playbook_dir }}/../bin/"
    delete: true

- name: Ensure ~/.config/htop exists
  file:
    path: ~/.config/htop
    state: directory

- name: Copy htoprc
  copy:
    dest: ~/.config/htop/htoprc-ttj
    src: ~/.config/htop/htoprc
  register: copied

- name: Adjust htoprc to VMs
  when: copied.changed
  shell: |
    sed -re 's/(column_meters_0=AllCPUs)2/\1/' \
      -re 's/(show_cpu_frequency)=1/\1=0/' \
      -re 's/(show_cpu_temperature)=1/\1=0/' \
      ~/.config/htop/htoprc-ttj > \
      ~/.config/htop/htoprc
