---
- name: Copy ~/.* to server
  copy:
    dest: "~/{{ item }}"
    src: "{{ playbook_dir }}/../{{ item }}"
  loop: "{{ conf_files }}"

- name: Sync ~/bin to server
  synchronize:
    dest: ~/bin/
    src: "{{ playbook_dir }}/../bin/"
    delete: true

- name: Ensure ~/.config/htop exists
  file:
    path: ~/.config/htop
    state: directory

- name: Copy htoprc
  copy:
    dest: ~/.config/htop/htoprc
    src: ~/.config/htop/htoprc
