---
- name: Ensure keepalived is installed
  package:
    name: keepalived
    state: present

- name: Render keepalived.conf
  template:
    src: keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
    mode: "0644"
  notify: restart keepalived

- name: Create keepalived systemd override directory
  ansible.builtin.file:
    path: /etc/systemd/system/keepalived.service.d
    state: directory
    mode: "0755"

- name: Make keepalived depend on wg-quick@wg0
  ansible.builtin.copy:
    dest: /etc/systemd/system/keepalived.service.d/wg0.conf
    mode: "0644"
    content: |
      [Unit]
      Wants=wg-quick@wg0.service
      After=wg-quick@wg0.service
  notify:
    - restart keepalived

- name: Render wg-vip-failover.sh
  template:
    src: wg-vip-failover.sh.j2
    dest: /usr/local/sbin/wg-vip-failover.sh
    mode: "0755"
