---
- name: Ensure wireguard is installed
  package:
    name: >-
      {{
      'wireguard' if ansible_facts.distribution == "Ubuntu"
      else 'wireguard-tools'
      }}
    state: present

- name: Ensure wireguard directory exists
  file:
    path: /etc/wireguard
    state: directory
    mode: "0700"

- name: Rotate private key
  shell: |
    umask 077
    wg genkey
  register: privatekey_raw

- name: Derive public key
  shell: echo "{{ privatekey_raw.stdout | trim }}" | wg pubkey
  register: publickey_raw

- name: Resolve SSH endpoint (from local ssh config)
  delegate_to: main
  become: false
  changed_when: false
  shell: ssh -G {{ inventory_hostname }} | awk '$1 == "hostname" {print $2}'
  register: ssh_resolved

- name: Set WireGuard facts
  set_fact:
    wg_private_key: "{{ privatekey_raw.stdout | trim }}"
    wg_public_key: "{{ publickey_raw.stdout | trim }}"
    wg_endpoint: >-
      {{
        '' if inventory_hostname in groups['laptops']
        else (ssh_resolved.stdout | trim)
      }}
    wg_ip: "{{ wg_ip }}"

- name: Build peer list
  set_fact:
    wg_peers: []

- name: Populate peer list
  set_fact:
    wg_peers: >
      {{ wg_peers + [ {
        'wg_ip': hostvars[item].wg_ip,
        'wg_public_key': hostvars[item].wg_public_key,
        'wg_endpoint': hostvars[item].wg_endpoint,
      } ] }}
  loop: "{{ groups['all'] }}"
  when: item != inventory_hostname and hostvars[item].wg_ip is defined

- name: Render wg0.conf
  template:
    src: wg0.conf.j2
    dest: /etc/wireguard/wg0.conf
    mode: "0600"
  notify:
    - reload wireguard daemon
    - restart wireguard
