---
- name: Ensure dedicated SSH user exists
  user:
    name: "{{ wg_user }}"
    shell: /bin/bash
    create_home: yes
    state: present

- name: Enable SSH for {{ wg_user }}
  copy:
    dest: /etc/ssh/sshd_config.d/10-wireguard.conf
    content: |
      AllowGroups {{ wg_user }}

- name: NOPASSWD for setting peers via the wg command
  copy:
    dest: /etc/sudoers.d/10-wireguard
    content: |
      {{ wg_user }} ALL=(root) NOPASSWD: /usr/bin/wg
    mode: "0400"

- name: Ensure .ssh directory exists
  file:
    path: "/home/{{ wg_user }}/.ssh"
    state: directory
    owner: "{{ wg_user }}"
    group: "{{ wg_user }}"
    mode: "0700"

- name: Copy SSH config
  copy:
    dest: "/home/{{ wg_user }}/.ssh/config"
    content: |
      Host 10.200.0.*
        StrictHostKeyChecking accept-new
        Port 55522
        ConnectTimeout 5
        IdentityFile	~/.ssh/id_{{ wg_user }}

    owner: "{{ wg_user }}"
    group: "{{ wg_user }}"
    mode: "0600"

- name: Clear known_hosts
  file:
    path: "/home/{{ wg_user }}/.ssh/known_hosts"
    state: absent

- name: Rotate common SSH key
  delegate_to: main
  become: false
  run_once: true
  shell: |
    KF=/tmp/id_$(uuidgen)
    umask 077
    ssh-keygen -t ed25519 -f $KF -N '' -q
    cat $KF.pub
    echo
    cat $KF
    rm $KF*
  register: keypair

- name: Install public key into user's authorized_keys
  copy:
    dest: "/home/{{ wg_user }}/.ssh/authorized_keys"
    content: "{{ keypair.stdout | split('\n\n') | first }}\n"
    owner: "{{ wg_user }}"
    group: "{{ wg_user }}"
    mode: "0600"

- when: vip_prio is defined
  block:
    - name: Copy public key
      copy:
        dest: "/home/{{ wg_user }}/.ssh/id_{{ wg_user }}.pub"
        content: "{{ keypair.stdout | split('\n\n') | first }}\n"
        owner: "{{ wg_user }}"
        group: "{{ wg_user }}"
        mode: "0600"

    - name: Copy private key
      copy:
        dest: "/home/{{ wg_user }}/.ssh/id_{{ wg_user }}"
        content: "{{ keypair.stdout | split('\n\n') | last }}\n"
        owner: "{{ wg_user }}"
        group: "{{ wg_user }}"
        mode: "0600"
